1. How likely is it that you roll doubles when rolling two dice?

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%config InlineBackend.figure_format = 'retina'
import viz 



In [21]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], size = (n_trials, n_dice))
rolls

#trials, number of trials
#dice, number of dice rolls

array([[4, 2],
       [1, 6],
       [2, 2],
       ...,
       [2, 3],
       [1, 1],
       [4, 4]])

In [34]:
sums_by_trial = rolls.sum(axis=1)
sums_by_trial
doubles_boolean = sums_by_trial % 2 == 0
doubles = doubles_boolean 

double_probability = doubles.mean()
double_probability

#wins = sums_by_trial > 12


0.5059

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [36]:
n_trials = nrows = 10_000
n_coins = ncols = 8

flips = np.random.choice([0,1], size = (n_trials, n_coins))
flips


array([[0, 0, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 1, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 1, 1, ..., 1, 1, 0]])

In [56]:
flip_sums = sums_by_row = flips.sum(axis=1)
three_heads = sums_by_row == 3
three_heads_rate = three_heads.astype(int).mean()
print('3heads rate:',three_heads_rate)

not_three_heads_rate = 1 - three_heads_rate

print('not 3 heads rate:',not_three_heads_rate)


3heads rate: 0.2174
not 3 heads rate: 0.7826


3. There are approximately 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [60]:
#Student selected is data scientist 
n_trials = nrows = 10_000
n_billboards = ncols = 2

ds_bill = np.random.choice([0, 1], size = (n_trials, n_billboards))
ds_b = ds_bill.sum(axis=1)

double_bills = ds_b > 1
both_billboards = double_bills.mean()

both_billboards * (1/3)

#wins = sums_by_trial > 12

0.08526666666666667

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values.

In [63]:
np.random.normal(loc = 3, scale = 1.5, size = 1)





array([4.05237246])

5. Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?



In [66]:
file_corrupt = (1/250)

np.random.random
n_trials = nrows = 50
n_outcomes = ncols = 1

virus_50 = np.random.random(size = (n_trials, n_outcomes))

boolean_mask = virus_50 >= file_corrupt

boolean_mask




array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?